[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dAngr"
version = "0.0.13"
authors = [
  { name="Jorn Lapon", email="jorn.lapon@kuleuven.be" },
  { name="Dairo de Ruck", email="dairo.deruck@kuleuven.be"},
  { name="Jef Jacobs", email="jef.jacobs@kuleuven.be"}
]
description = "Debugging with Angr package"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[project.scripts]
dAngr = "dAngr.run:run"


[tool.setuptools]
license-files = []

[project.urls]
Homepage = "https://github.com/angr-debugging/dAngr"
Issues = "https://github.com/angr-debugging/dAngr/issues"